### ISSUE TITLE
Should exceptions be included in a coding standard's title?

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/CodingGuidelines#87]
How much of an explanation should be included in a coding standards title.  For example, should a common exception be included in the title:
> **AVOID omitting braces, except for the simplest of single-line if statements.**

versus
> **AVOID omitting braces**
> Exceptions:
> 
> The simplest of single-line `if` statements
> Example...

**Comment by MarkMichaelis** [comment]
The balance here is between succinctness and clarity.  
There has been a fair amount of precedence in this area.  With the words AVOID, CONSIDER, DO, and DO NOT we make a clear distinction between *usually* and *always*.  See the guidelines listing at [Coding-Guidelines](https://github.com/IntelliTect-Samples/EWU-CSCD379-2020-Winter/wiki/Coding-Guidelines) (temporary URL) for a list of sample guidelines.

In the example, people are specifically looking for guidance on when they can omit braces. To bury the exception is likely to cause the guidance to be lost.  Alternatively, perhaps in this case, that is the goal?  Perhaps **AVOID** is clear enough and specific exception requires mentioning? However, given the guideline is relatively succinct, is the exception inclusion optimizing functionality?

**Comment by Keboo** [comment]
Updated link to the guidelines: https://intellitect.github.io/CodingStandards/coding/csharp.html

**Comment by MarkMichaelis** [comment]
I was providing the other list because I thought it was significantly longer and provided more precedence.  However, I agree that the "approved" list is better so link switched.

**Comment by ascott18** [comment]
To me, https://intellitect.github.io/CodingStandards/coding/csharp.html is very hard to read through because of its formatting. I think a tabular format may be better suited, e.g.

| Rule Name | Rule Description | Exceptions | Example |
|---|---|---|---|
|DO: Prefix Fields | Prefix fields (if they are indeed needed) with underscore and then use ‘PascalCasing’ and wrap them with a property (even if the end result is private) | Exception: Unless you need to pass a member value by ref, and it cannot be a local variable.  | Example: Maintaining an internal reference count using Interlocked. This largely removes the need for readonly fields in favor of properties. |

**Comment by Keboo** [comment]
@ascott18 formatting issue filed #91

**Comment by MarkMichaelis** [comment]
Amen... I agree with the need for a format improvement.  

I do think we want the title/rule name horizontally - as sometimes they are quite lengthy, too lengthy for short cell.  While succinctness is sought after and valued, we would choose clarity over brevity.  The hope is that, **The guideline title provides enough information to follow the guidance, but not necessarily enough information to know the details of why the guideline is important.**

**Comment by Keboo** [comment]
As per discussion, we will evaluate on a case by case basis whether to include exceptions in the rule title.
